app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from project.settings import MEDIA_ROOT, MEDIA_URL 
urlpatterns = [
    path('', views.home,name='home'),
    path('login', views.login,name='login'),
    path('logout', views.logout,name='logout'),
    path('signup', views.signup,name='signup'),
    path('courses', views.courses,name='courses'),
    path('schedules', views.schedules,name='schedules'),
    path('report', views.report,name='report'),
    path('contactus', views.contactus,name='contactus'),
    path('blog', views.blog,name='blog'),
    path('news', views.news,name='news'),
    path('course/<str:slug>', views.coursePage , name='coursePage'),
    path('enroll/<str:slug>', views.enroll , name='enroll'),
    path('schedule/<str:slug>', views.schedule , name='schedule'),
]+ static(MEDIA_URL, document_root=MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from dataclasses import field
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, UserManager,User

# Create your models here.
# this will store the user details in an abstract class
class UserManager(BaseUserManager):
    def create_user(self, name, email, password):
        user = self.model(name=name, email=email, username=email.split("@")[0],password=password)
        user.set_password(password)
        user.save(using=self._db)
        print("User Created",user.name,user.email,user.username)
        return user

class User(AbstractBaseUser):
    name = models.CharField(db_column='Name', max_length=35)
    email = models.CharField(db_column='Email', max_length=100, primary_key=True)
    username = models.CharField(db_column='Username', max_length=100)
    password = models.CharField(db_column='Password', max_length=100)
    

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

class Course(models.Model):
    name = models.CharField(max_length = 30, null = True)
    slug = models.CharField(max_length = 50, null = False, unique=True)
    description = models.CharField(max_length = 200, null = True)
    days = models.CharField(max_length=30, null = True)
    price = models.CharField(max_length = 50, null = True)
    thumbnail = models.ImageField(upload_to = "files/thumbnail", null=True)
    def __str__(self):
        return self.name


class CourseProperty(models.Model):
    description  = models.CharField(max_length = 100 , null = False)
    course = models.ForeignKey(Course , null = False , on_delete=models.CASCADE)

    class Meta : 
        abstract = True


class Tag(CourseProperty):
    pass
    
class Prerequisite(CourseProperty):
    pass

class Learning(CourseProperty):
    pass

class Video(models.Model):
    title = models.CharField(max_length = 100, null = True)
    course = models.ForeignKey(Course , null = False, on_delete=models.CASCADE)
    serial_number = models.IntegerField(null = True)
    video_id = models.CharField(max_length=100, null = True)
    is_preview = models.BooleanField(default=False)
    def __str__(self):
        return self.title


class Schedule(models.Model):
    name = models.CharField(max_length = 30, null = True)
    slug = models.CharField(max_length = 50, null = False, unique=True)
    description = models.CharField(max_length = 200, null = True)
    days = models.CharField(max_length = 30, null = True)
    timing = models.CharField(max_length = 30, null = True)
    trainer = models.CharField(max_length = 30, null = True)
    phno = models.CharField(max_length=20, null = True, unique=True)
    mailid = models.CharField(max_length=100, null=True, unique=True)
    thumbnail = models.ImageField(upload_to = "files/thumbnail", null=True)
    def __str__(self):
        return self.name

# this will store user details in database
# class UserInfo(models.Model):
#     name = models.CharField(db_column='Name', max_length=35)
#     email = models.CharField(db_column='Email', max_length=100, primary_key=True)

app/templates/Courses.html
{% load static %}
{% load course_custom_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Fitness center</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Handlee&family=Nunito&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Flaticon Font -->
    <link href="lib/flaticon/font/flaticon.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'coursestyle.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
    <!-- Navbar Start -->
    <div class="container-fluid bg-light position-relative shadow">
        <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0 px-lg-5">
            <a href="" class="navbar-brand font-weight-bold text-secondary" style="font-size: 50px;">
                <i class="fas fa-dumbbell"></i>
                <span class="text-primary">FitNezZone</span>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav font-weight-bold mx-auto py-0">
                    <a href="/" class="nav-item nav-link">Home</a>
                    <a href="#" class="nav-item nav-link">Courses</a>
                    <a href="schedules" class="nav-item nav-link">Schedule</a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->


    <!-- Header Start -->
    <div class="container-fluid bg-primary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
            <h3 class="display-3 font-weight-bold text-white">Fitness center</h3>
        </div>
    </div>
    <!-- Header End -->

    <div class="container-fluid">
        <br>
        <div class="row">
            {% for course in courses %}
            <div class="col mx-auto">
                <div class="card mx-auto" style="width: 20rem;">
                    <img class="card-img-top" src="{{course.thumbnail.url}}" alt="Card image cap" width="100px" height="200px">
                    <div class="card-body">
                    <h5 class="card-title">Name: {{course.name}}</h5>
                    <p class="card-text">Description: {{course.description}}</p>
                    <p class="card-text">Days: {{course.days}}</p>
                    <p class="card-text">Price: {{course.price}}</p>
                    </div>

                    {% is_enrolled request course as enrolled %}
                    <div class="row no-gutters">
                    {% if enrolled %}
                    <div class="col">
                        <a href="/course/{{course.slug}}" class="btn btn-light">Start Course</a>
                    </div>
                    {% else %}
                    <div class="col border-right">
                        <a href="enroll/{{course.slug}}" class="btn btn-light">Register Now</a>
                        <a href="course/{{course.slug}}" class="btn btn-light">Show More</a>
                    </div>
                    {% endif %}
                    </div>
                    <br>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

app/templates/Home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FitNezZone</title>
    <link rel="stylesheet" href="{% static 'homestyle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    
</head>

<body>
    <header class="header">
        <a href="#" class="logo">
        <i class="fas fa-dumbbell"></i>FitNezZone
        </a>
        <nav class="navbar">
            <a href="#">Home</a>
            <a href="{% url 'courses' %}">Courses</a>
            <a href="{% url 'schedules' %}">Schedule</a>
            <a>|</a>
            {% if request.user.is_authenticated %}
            <a>Welcome {{user.username}},</a>
            <a href="report">Report</a>
            <a href="logout">Logout</a>
            {% else %}
            <a href="report">Report</a>
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'signup' %}" class="btn">Sign Up</a> 
            {% endif %}
        </nav>
    </header>
    <section class="home">
        <div class="max-width">
            <div class="home-content">
                <h3>help for ideal <br> body fitness</h3>
                <a href="{% url 'courses' %}"><button class="btn">Get started</button></a>
            </div>
            <div class="home-image">
                <img src="{% static 'gif.gif' %}" alt="">
            </div>
        </div>
    </section>

    <section class="home2">
        <div class="max-width2" id="aboutus">
            <div class="home-content">
                <h3>About us</h3><br>
                <p>Let’s make healthy happen!</p><br>
                <p>FITNESS FOR ALL</p><br>
                <p>Fitness is not the prerogative of a few. It is the right of everyone on the same premise, we committed to make Healthy happen to all. Fitness have become an essential component for many people who want to train at their own pace, keep the motivation high and overall improving their life.</p><br>
                <p>The keys to having a successful workout and completing your fitness goals are motivating with someone else, entertaining yourself and enjoying what you do. If you make boring workouts, your fitness plans can quickly lose pace. So make your exercise fun and you’ll stick to it for a very long time. And for that we offer a various range of courses not only that includes heavy workouts but also for pregnant women’s and elderly people who would like to have a fun and relaxing workout which would benefit them eventually and to lead a healthy lifestyle.</p><br>
                <p>Our community provides courses which includes regular workouts along with few martial arts and some entertaining workouts that you want to feel light like Zumba and so on, The Fitnezzone team is comprised of experienced, passionate professionals who are dedicated to obtaining, creating, and disseminating relevant, timely, high-quality content, and to providing comprehensive strength and conditioning, and mind/body wellness programs.</p><br>
                <p>So Get stronger and fitter with us !!</p>
            </div>
        </div>
    </section>
    
    <section class="home3">
        <div class="max-width3">
            <div class="home-content">
                <h3>Trainer Details<br><br></h3>
            </div>
        </div>
        <div class="pics0">
            <div class="home1-image">
                <img src="{% static 'Id 1.jpg' %}" alt="" width="350">
            </div>
            <div class="home2-image">
                <img src="{% static 'Id 2.jpg' %}" alt="" width="350">
            </div>
        </div>
        <div class="pics">
            <div class="home3-image">
                <img src="{% static 'Id 3.jpg' %}" alt="" width="350">
            </div>
            <div class="home4-image">
                <img src="{% static 'Id 4.jpg' %}" alt="" width="350">
            </div>
        </div>
    </section>

    <footer class="footer">        
        <div>
            <h3>Company</h3>
            <a href="#aboutus">About Us</a><br>
            <a href="">Terms and Conditions</a><br>
            <a href="">Privacy Policy</a><br>
            <a href="news">NewsLetter</a>
        </div>
        <div style="float: right;">
            <h3>Members</h3>
            <a href="">FAQ</a><br>
            <a href="blog">Blog</a><br>
            <a href="contactus">Contact Us</a>
        </div>
    </footer>
</body>
</html>

app/templates/Newsletter.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FitNezZone</title>
    <link rel="stylesheet" href="{% static 'blogstyle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
</head>

<body>
    <header class="header">
        <a href="#" class="logo">
        <i class="fas fa-dumbbell"></i>FitNezZone
        </a>
        <nav class="navbar">
            <a href="/">Home</a>
        </nav>
    </header>
    <section class="home">
        <div class="max-width">
            <div class="home-content">
                <h3>STRESS IMPACTS ON WEIGHT</h3>
            </div>
            <div class="home-image">
                <img src="{% static 'nl1.jpg' %}" alt="">
            </div>      
        </div>
    </section>

    <section class="home2">
        <div class="max-width2" id="aboutus">
            <div class="home-content">
                <h3>NewsLetter</h3><br>
                <p>Please tell me I’m not alone in feeling stressed out.</p>
                <p>Don’t get me wrong, I LOVE this time of year, but I’ve been feeling overwhelmed by how much I have to, and WANT, to do!</p>
                <p>Between work, family, friends, parties, etc. it’s just… a lot. </p>
                <p>I know I have to keep it in check though – stress is your waistline’s worst enemy!</p>
                <p>Stress impacts your weight, adjust your routine, holiday routine, holiday survival guide, how to build a routine, healthy routines, my daily routine</p>
        </div>
    </section>
    
    <section class="home2">
        <div class="max-width2">
            <div class="home-content">
                <h3>STRESS MAKES YOU GAIN WEIGHT</h3>
                <p>One day of unexpected stress may not be a big deal, but an entire season feeling overwhelmed (even with good stuff!) is. </p>
                <p>Chronic stress elevates your cortisol levels – aka your stress hormones.</p>
                <p>That means when we’re stressed our appetite increases.
                </p>
                <p>Increased appetite leads to excess weight gain and trouble losing weight. </p>
        </div>
    </section>

    <section class="home2">
        <div class="max-width2">
            <div class="home-content">
                <h3>WHY YOU’RE GAINING BELLY FAT</h3><br>
                <p>The worst part? Stress impacts where you gain weight.  </p>
                <p>Most of the excess fat will end up in your stomach.</p>
                <p>I know, I wish we could just send it to our boobs or our butts, right? It’s like some cruel joke.
                </p>
                <p>Stress impacts your weight, adjust your routine, holiday routine, holiday survival guide, how to build a routine, healthy routines, my daily routine </p>
        </div>
    </section>

    <section class="home2">
        <div class="max-width2">
            <div class="home-content">
                <h3>HOW TO DEAL WITH STRESS</h3><br>
                <p>Whenever I start feeling super stressed I always hit pause, turn on some happy music, and make myself a warm coffee (½ caff lately) with my Miss Congeniality mood boost! </p><br>
                <p>It’s loaded with vitamins, minerals and adaptogens that help reduce my stress and literally make me feel so much happier. </p><br>
                <p>You’ve got to go read other girls’ reviews too! It’s insane!
                </p>
                <p>Get yours here.</p>
                <p>Stress impacts your weight, adjust your routine, holiday routine, holiday survival guide, how to build a routine, healthy routines, my daily routine</p>
                <p>When I pair Miss Congeniality with a healthy daily routine – it’s a GAME CHANGER!</p>
                <p>I feel happier, calmer, and way more ready to take on anything the week throws at me.</p>
                <p>I can’t wait for you to experience it too!</p>
                <p>Join our community and feel happy </p>
        </div>
    </section>

    
</body>
</html>

app/templates/Schedule.html
{% load static %}
{% load schedule_custom_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Fitness center</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Handlee&family=Nunito&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Flaticon Font -->
    <link href="lib/flaticon/font/flaticon.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'coursestyle.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navbar Start -->
    <div class="container-fluid bg-light position-relative shadow">
        <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0 px-lg-5">
            <a href="" class="navbar-brand font-weight-bold text-secondary" style="font-size: 50px;">
                <i class="fas fa-dumbbell"></i>
                <span class="text-primary">FitNezZone</span>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav font-weight-bold mx-auto py-0">
                    <a href="/" class="nav-item nav-link">Home</a>
                    <a href="courses" class="nav-item nav-link">Courses</a>
                    <a href="{% url 'schedules' %}" class="nav-item nav-link">Schedule</a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->


    <!-- Header Start -->
    <div class="container-fluid bg-primary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
            <h3 class="display-3 font-weight-bold text-white">Fitness center</h3>
        </div>
    </div>
    <!-- Header End -->
    <div class="container-fluid">
        <br>
        <div class = "row">
            {% for schedule in schedules %}
            <div class="col mx-auto">
                <div class = "card mx-auto" style="width: 20rem;">
                    <img class="card-img-top" src="{{schedule.thumbnail.url}}" alt="Card image cap" width="100px" height="200px">
                    <div class="card-body">
                        <h5 class="card-title">Name: {{schedule.name}}</h5>
                        <p class="card-text">Description: {{schedule.description}}</p>
                        <p class="card-text">Days: {{schedule.days}}</p>
                        <p class="card-text">Timing: {{schedule.timing}}</p>
                        <p class="card-text">Trainer: {{schedule.trainer}}</p>
                        <p class="card-text">Ph_No: {{schedule.phno}}</p>
                        <p class="card-text">Mail_Id: {{schedule.mailid}}</p>
                    </div>

                    {% is_scheduled request schedule as scheduled %}
                    <div class="row no-gutters">
                    {% if scheduled %}
                    <div class = "col">
                        <a>Scheduled</a>
                    </div>
                    {% else %}    
                    <div class="col border-right">
                        <a href ="schedule/{{schedule.slug}}" class="btn btn-light">Enroll Now</a>
                    </div>
                    {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

app/templates/Signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name=""viewport" content="width=device-width, initial-scale=1.0">
    <title>Register User</title>
</head>
<body>
    <h3>Register Form</h3>
    <hr/>
    {% if messages %}
        {% for message in messages %}
        <p>{{messages}}</p> 
        {% endfor %}
    {% endif %}
    <form method="post" action="" id="form">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" />
    </form>
</body>
</html>

app/templates/contact_us.html
<html>
<head>
<link rel="stylesheet" href="contact.css">
</head>

<body>
<h1> CONTACT US </h1>
<h2> 
NO - 12,<br>
Kennady Street<br>
Coimbatore - 39<br>
Tamilnadu,<br>
India<br>
</h2>
<h2>
For enquiry please reach out us on <a href="fitnezzone.contact@companymail.com ">fitnezzone.contact@companymail.com</a>
</h2>

</body>
</html>

app/templates/course_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<style>
    #video_list{
        overflow-y: scroll;
    }
</style>

<head>
    <meta charset="utf-8">
    <title>Fitness center</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Handlee&family=Nunito&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Flaticon Font -->
    <link href="lib/flaticon/font/flaticon.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'coursestyle.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navbar Start -->
    <div class="container-fluid bg-light position-relative shadow">
        <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0 px-lg-5">
            <a href="" class="navbar-brand font-weight-bold text-secondary" style="font-size: 50px;">
                <i class="fas fa-dumbbell"></i>
                <span class="text-primary">FitNezZone</span>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav font-weight-bold mx-auto py-0">
                    <a href="/" class="nav-item nav-link">Home</a>
                    <a href="{% url 'courses' %}" class="nav-item nav-link">Courses</a>
                    <a href="{% url 'schedules' %}" class="nav-item nav-link">Schedule</a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->


    <!-- Header Start -->
    <div class="container-fluid bg-primary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
            <h3 class="display-3 font-weight-bold text-white">Fitness center</h3>
        </div>
    </div>
    <!-- Header End -->

    <div class="container-fluid">
        <div>  
        <br>
        <br>
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <div class="mx-auto">
                        <iframe id="player" class="mx-auto" width="1000" height="450" src="https://www.youtube.com/embed/{{video.video_id}}" 
                        title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; 
                        gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>  
                <div class="col-3">
                    <div class="border">
                        <ul id='video_list' class="list-group">
                            {% for video in course.video_set.all %}
                                <li class="list-group-item"><a href="?lecture={{video.serial_number}}">{{video}}</a></li>
                            {% endfor %} 
                        </ul>  
                    </div>
                </div>
            </div>
        </div> 
        <div class="mt-3">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title">{{course.name}}</h5>
                  <p class="card-text">{{course.description}}</p>
                </div>
            </div>
        </div>
    </div>
    <script>
        var player;
        var video_list;
        //window.onload = () =>{
        //    player = document.getElementById('player')
        //    maintainRatio() 
       // }
        
        document.onreadystatechange=function(){
            if(document.readyState == 'interactive'){
                player=document.getElementById("player")
                video_list = document.getElementById("video_list")

                maintainRatio()
            }
        }
        function maintainRatio(){

            console.log({
                width : player.width,
                cw : player.clientWidth,
                h : player.height,
                ch : player.clientHeight,
            });
            var w = player.clientWidth
            var h = (w*9)/16
            console.log({w , h});
            player.height = h
            video_list.style.maxHeight = h + 'px'
        }

        window.onresize = mentainRatio
    </script>
    <style>
        /* width */
        ::-webkit-scrollbar {
          width: 10px;
        }
        
        /* Track */
        ::-webkit-scrollbar-track {
          background: #f1f1f1; 
        }
         
        /* Handle */
        ::-webkit-scrollbar-thumb {
          background: #888; 
        }
        
        /* Handle on hover */
        ::-webkit-scrollbar-thumb:hover {
          background: #555; 
        }
    </style>
</body>
</html>

app/templates/regcourse.html
{% load static %}
{% load course_custom_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Fitness center</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Handlee&family=Nunito&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Flaticon Font -->
    <link href="lib/flaticon/font/flaticon.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'coursestyle.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navbar Start -->
    <div class="container-fluid bg-light position-relative shadow">
        <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0 px-lg-5">
            <a href="" class="navbar-brand font-weight-bold text-secondary" style="font-size: 50px;">
                <i class="fas fa-dumbbell"></i>
                <span class="text-primary">FitNezZone</span>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav font-weight-bold mx-auto py-0">
                    <a href="/" class="nav-item nav-link">Home</a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->


    <!-- Header Start -->
    <div class="container-fluid bg-primary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
            <h3 class="display-3 font-weight-bold text-white">Fitness center</h3>
        </div>
    </div>

    <div class="container-fluid">
        <br>
        <h2>You've Successfully Registered the Course</h2>
    </div>
</body>
</html>